import profileImage from './drylake1small.jpg'

export const defaultUser = {
  name: 'Spencer Lee Tiberi',
  image: profileImage,
  bio:
    'Born in 1991 in Sparks, NV, he was raised in Las Vegas and currently lives in Cambridge, MA.',
  stats: {
    Creativity: 8,
    Drive: 8,
    Charisma: 8,
    Flexibility: 7,
    Wit: 9,
    'Emotional Intelligence': 9,
    'Learning Capacity': 8,
    'Time Management': 6,
    'Problem Solving': 8,
    Mentorship: 8,
    'Project Management': 7,
    'Public Speaking': 8,
    'Business Strategy': 7,
    Writing: 7,
    Programming: 7,
  },
}

export const friends = [
  defaultUser,
  {
    name: 'Levi Tiberi',
    image: profileImage,
    bio:
      'Born in 1994 in Henderson, NV, he was raised in Las Vegas, where he currently lives.',
    stats: {
      Creativity: 10,
      Drive: 8,
      Charisma: 7,
      Flexibility: 6,
      Wit: 8,
      'Emotional Intelligence': 6,
      'Learning Capacity': 8,
      'Time Management': 7,
      'Problem Solving': 7,
      Mentorship: 6,
      'Project Management': 8,
      'Public Speaking': 6,
      'Business Strategy': 8,
      Writing: 7,
      Programming: 3,
    },
  },
  {
    name: 'Jada Lee',
    image: profileImage,
    bio:
      'Born in 2000 in Los Angles, CA, she was raised in MN and currently lives in Cambridge, MA.',
    stats: {
      Creativity: 6,
      Drive: 9,
      Charisma: 8,
      Flexibility: 9,
      Wit: 5,
      'Emotional Intelligence': 8,
      'Learning Capacity': 8,
      'Time Management': 10,
      'Problem Solving': 7,
      Mentorship: 8,
      'Project Management': 8,
      'Public Speaking': 7,
      'Business Strategy': 9,
      Writing: 8,
      Programming: 4,
    },
  },
  {
    name: 'Brandon Belchar',
    image: profileImage,
    bio:
      'Born in 1995 in Maui, HI, he was raised in Las Vegas, where he currently lives.',
    stats: {
      Creativity: 7,
      Drive: 6,
      Charisma: 6,
      Flexibility: 8,
      Wit: 7,
      'Emotional Intelligence': 6,
      'Learning Capacity': 8,
      'Time Management': 7,
      'Problem Solving': 8,
      Mentorship: 4,
      'Project Management': 7,
      'Public Speaking': 6,
      'Business Strategy': 5,
      Writing: 6,
      Programming: 10,
    },
  },
]

export const models = [
  {
    name: 'LeBron James',
    image: profileImage,
    bio:
      'Born in 1991 in Sparks, NV, he was raised in Las Vegas and currently lives in Cambridge, MA.',
    stats: {
      intelligence: 8,
      projectManagement: 4,
      creativity: 4,
      timeManagement: 9,
      publicSpeaking: 9,
      emotionalIntelligence: 7,
      mentorship: 8,
      learningCapacity: 8,
      flexibility: 8,
      writing: 5,
      programming: 0,
      athletisism: 10,
      drive: 9,
    },
  },
  {
    name: 'Jon Stewart',
    image: profileImage,
    bio:
      'Born in 1991 in Sparks, NV, he was raised in Las Vegas and currently lives in Cambridge, MA.',
    stats: {
      intelligence: 9,
      projectManagement: 4,
      creativity: 4,
      timeManagement: 9,
      publicSpeaking: 9,
      emotionalIntelligence: 7,
      mentorship: 8,
      learningCapacity: 8,
      flexibility: 8,
      writing: 9,
      programming: 0,
      athletisism: 1,
      drive: 9,
      wit: 10,
    },
  },
  {
    name: 'James Bond',
    image: profileImage,
    bio:
      'Born in 1991 in Sparks, NV, he was raised in Las Vegas and currently lives in Cambridge, MA.',
    stats: {
      intelligence: 9,
      projectManagement: 4,
      creativity: 4,
      timeManagement: 9,
      publicSpeaking: 9,
      emotionalIntelligence: 7,
      mentorship: 8,
      learningCapacity: 8,
      flexibility: 8,
      writing: 9,
      programming: 0,
      athletisism: 1,
      drive: 9,
      wit: 10,
      confidence: 10,
      focus: 8,
      problemSolving: 9,
      charisma: 10,
    },
  },
]
